// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sprinkler.proto

package org.DS.gerryproject.SmartFarmingGRPC;

public interface sprinklerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartFarmingGRPC.sprinklerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string aname = 4;</code>
   */
  java.lang.String getAname();
  /**
   * <code>string aname = 4;</code>
   */
  com.google.protobuf.ByteString
      getAnameBytes();

  /**
   * <code>string status = 5;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 intensity = 6;</code>
   */
  int getIntensity();

  /**
   * <code>int32 range = 7;</code>
   */
  int getRange();
}
